root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main"
bin = "tmp/main"
delay = 1000
include_ext = ["go", "env"]
exclude_dir = ["tmp", "vendor", "docs"]
exclude_file = []
exclude_regex = ["_test.go"]

[log]
time = true

[misc]
clean_on_exit = true
